### ISSUE TITLE
Il pulsante #start deve essere un tag button

### ISSUE THREAD

**Issue by michelebruno** [drawwithcode/2020-ffmv#2]
Il pulsante con `id="start"` con cui parte `detectFace` deve essere un `<button>`, altrimenti l'attributo `disabled` viene letto e l'utente può cliccarlo prima che il caricamento sia concluso.

Inoltre, dato che la funzione `start()` elimina il pulsante, appare questo errore.

![immagine](https://user-images.githubusercontent.com/43304601/104846875-1055b080-58dd-11eb-808f-83bfaf8238dd.png)

**Comment by federicopozzi** [comment]
fixed
